modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/MaxJonsi/overpowered/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/MaxJonsi/overpowered"
authors="MaxJonsi"
description='''
Superpowers, animated weapons, mobs, magic and structures.
Custom 3D models and animations powered by GeckoLib.
'''

[[mixins]]
config="overpowered.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4.9,)"
    ordering="AFTER"
    side="BOTH"
